[build]
  command = "npm run build"
  publish = "dist/autowash-hub"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/angular-runtime"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
