import { Component, PLATFORM_ID, Inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { environment } from '../../../../../environments/environment';
import Swal from 'sweetalert2';

@Component({
  selector: 'app-admin-register',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './admin-register.component.html',
  styleUrl: './admin-register.component.css',
  host: { ngSkipHydration: 'true' },
})
export class AdminRegisterComponent {
  admin = {
    first_name: '',
    last_name: '',
    email: '',
    phone: '',
    password: '',
    confirm_password: '',
    // admin_key removed temporarily
  };

  termsAccepted = false;
  errorMessage = '';
  isLoading = false;
  isBrowser: boolean;
  showPassword = false;
  showConfirmPassword = false;

  constructor(
    private http: HttpClient,
    private router: Router,
    @Inject(PLATFORM_ID) platformId: Object
  ) {
    this.isBrowser = isPlatformBrowser(platformId);
  }

  togglePasswordVisibility(): void {
    this.showPassword = !this.showPassword;
  }

  toggleConfirmPasswordVisibility(): void {
    this.showConfirmPassword = !this.showConfirmPassword;
  }

  onSubmit(): void {
    // Reset error message
    this.errorMessage = '';
    this.isLoading = true;

    // Add terms validation
    if (!this.termsAccepted) {
      this.errorMessage = 'Please accept the terms and conditions';
      this.isLoading = false;
      return;
    }

    // Basic validation for required fields
    if (
      !this.admin.first_name ||
      !this.admin.last_name ||
      !this.admin.email ||
      !this.admin.phone ||
      !this.admin.password ||
      !this.admin.confirm_password
    ) {
      this.errorMessage = 'Please fill in all required fields';
      this.isLoading = false;
      return;
    }

    if (this.admin.password !== this.admin.confirm_password) {
      this.errorMessage = 'Passwords do not match';
      this.isLoading = false;
      return;
    }

    // Email validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(this.admin.email)) {
      this.errorMessage = 'Please enter a valid email address';
      this.isLoading = false;
      return;
    }

    const registrationData = {
      first_name: this.admin.first_name,
      last_name: this.admin.last_name,
      email: this.admin.email,
      phone: this.admin.phone,
      password: this.admin.password,
      // admin_id will be automatically generated by the backend
      // admin_key removed from data
    };

    console.log('Sending registration data to API:', {
      ...registrationData,
      password: '[REDACTED]',
    });

    // Step 1: request a verification code
    this.http
      .post(
        `${environment.apiUrl}/send_registration_code`,
        { email: this.admin.email },
        { headers: { 'Content-Type': 'application/json' } }
      )
      .subscribe({
        next: async (codeResp: any) => {
          console.log('Verification code response:', codeResp);

          // Step 2: prompt for 6-digit code
          const { value: code } = await Swal.fire({
            title: 'Enter Verification Code',
            input: 'text',
            inputLabel: 'A 6-digit code was sent to your email',
            inputPlaceholder: '123456',
            inputAttributes: {
              maxlength: '6',
              inputmode: 'numeric',
              autocapitalize: 'off',
              autocorrect: 'off',
            },
            showCancelButton: true,
            confirmButtonText: 'Verify & Register',
            preConfirm: (value) => {
              if (!/^\d{6}$/.test(value)) {
                Swal.showValidationMessage('Please enter a valid 6-digit code');
              }
              return value;
            },
          });

          if (!code) {
            this.isLoading = false;
            return;
          }

          const payload: any = { ...registrationData, verification_code: code };

          // Step 3: submit registration with code
          this.http
            .post(`${environment.apiUrl}/register_admin`, payload, {
              headers: { 'Content-Type': 'application/json' },
            })
            .subscribe({
              next: (response: any) => {
                this.isLoading = false;
                console.log('Response:', response);
                if (response.status.remarks === 'success') {
                  // Show success message before redirecting (only if in browser)
                  if (this.isBrowser) {
                    try {
                      Swal.fire({
                        title: 'Registration Submitted!',
                        text: 'Your account is pending approval by a super admin. You will be able to sign in once approved.',
                        icon: 'success',
                        confirmButtonText: 'OK',
                      }).then(() => {
                        this.router.navigate(['/admin-login']);
                      });
                    } catch (err) {
                      console.error('Error with browser API:', err);
                      this.router.navigate(['/admin-login']);
                    }
                  } else {
                    this.router.navigate(['/admin-login']);
                  }
                } else {
                  const errorMessage =
                    response.status.message || 'Registration failed';
                  this.errorMessage = errorMessage;

                  // Show error message
                  Swal.fire({
                    title: 'Registration Failed!',
                    text: errorMessage,
                    icon: 'error',
                    confirmButtonText: 'OK',
                  });
                }
              },
              error: (err) => {
                this.isLoading = false;
                console.error('Registration error:', err);
                this.errorMessage = 'Registration failed. Please try again.';
                Swal.fire({
                  title: 'Registration Failed!',
                  text: 'Registration failed. Please try again.',
                  icon: 'error',
                  confirmButtonText: 'OK',
                });
              },
            });
        },
        error: (error) => {
          this.isLoading = false;
          console.error('Send code error:', error);
          const msg =
            (error?.error?.status?.message as string) ||
            'Failed to send verification code.';
          this.errorMessage = msg;
          Swal.fire({
            title: 'Verification Failed!',
            text: msg,
            icon: 'error',
            confirmButtonText: 'OK',
          });
        },
      });
  }
}
